"$schema" = 'https://starship.rs/config-schema.json'

format = "$conda$python$character$directory$git_branch$git_status "

add_newline = false

[python]
format = '[(\($virtualenv\) )]($style)'
style = "yellow"
detect_extensions = []
detect_files = []
detect_folders = []

[conda]
format = '[(\($environment\) )]($style)'
style = "yellow"
ignore_base = true

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
vimcmd_symbol = "[❮](bold green)"
vimcmd_replace_one_symbol = "[❮](bold purple)"
vimcmd_replace_symbol = "[❮](bold purple)"
vimcmd_visual_symbol = "[❮](bold yellow)"

[directory]
format = "[$path]($style) "
style = "bold cyan"
truncation_length = 1
truncate_to_repo = false

[git_branch]
format = "[git:\\(](white)[$branch]($style)[\\)](white) "
style = "bold red"

[git_status]
format = "[$all_status]($style)"
style = "bold green"
conflicted = "❯"
ahead = ""
behind = ""
diverged = ""
up_to_date = ""
untracked = "❯"
stashed = ""
modified = "❯"
staged = "❯"
renamed = "❯"
deleted = "❯"
